---
kind: pipeline
type: docker
name: deploy

steps:
  - name: ssh commands
    image: appleboy/drone-ssh
    settings:
      port: 22
      host:
        from_secret: ssh_host
      username:
        from_secret: ssh_user
      key:
        from_secret: ssh_key
      script_stop: true
      script:
        - source .profile
        - cd selfhosted
        - git pull
        - docker compose config
        - docker compose up -d --remove-orphans --no-start --no-recreate
